#
# MAPBASE SOURCE 2013 CI
#
# Builds map tool projects every time a pull request which modifies the map tool code is opened.
# If you're using a fork of Mapbase, feel free to configure this to meet your repository's needs.
#
# See mapbase_build-base.yml for more information on how this works.

name: Build Map Tool Projects #(SP Release)

on:
  pull_request:
    branches:
      - develop
    paths:
      - '.github/workflows/mapbase_build-sp-rel-maptools.yml'
      - 'mp/src/vpc_scripts/**'
      - 'mp/src/utils/vbsp/**'
      - 'mp/src/utils/vvis/**'
      - 'mp/src/utils/vvis_launcher/**'
      - 'mp/src/utils/vrad/**'
      - 'mp/src/utils/vrad_launcher/**'
      - 'mp/src/mathlib/**'
      - 'mp/src/tier1/**'
      - 'mp/src/vgui2/vgui_controls/**'
      - 'mp/src/vscript/**'

jobs:
  maptools:
    strategy:
      matrix:
        configuration: [Release, Debug]
    uses: ./.github/workflows/mapbase_build-base.yml
    with:
      configuration: ${{ matrix.configuration }}
      branch: 'sp'
      project-group: 'maptools'
      solution-name: 'maptools'
